# Introduction

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Maria", "Luka", "Chris", np.nan],
    "Age": [25,27,44,35],
    "Occupatin": ["Engineer", "Competitive Eater", "Artist", "Scientist"]
})

In [ ]:
df

    Name  Age          Occupatin
0  Maria   25           Engineer
1   Luka   27  Competitive Eater
2  Chris   44             Artist
3    NaN   35          Scientist

## Data cleaning part 1

In [ ]:
df.isna()

    Name    Age  Occupatin
0  False  False      False
1  False  False      False
2  False  False      False
3   True  False      False

## Data cleaning Part 2

In [ ]:
import pandas as pd
from scipy import stats

df = pd.DataFrame({
    "Transaction_Amount": [100, 150, 200, 250, 300, 9999]
})

In [ ]:
df

   Transaction_Amount
0                 100
1                 150
2                 200
3                 250
4                 300
5                9999

In [ ]:
df['Z_Score'] = stats.zscore(df['Transaction_Amount'])

In [ ]:
df

   Transaction_Amount   Z_Score
0                 100 -0.474523
1                 150 -0.460833
2                 200 -0.447144
3                 250 -0.433454
4                 300 -0.419765
5                9999  2.235719

In [ ]:
df['Winsorized_Amount'] = stats.mstats.winsorize(df['Transaction_Amount'], limits=[0.05, 0.05])
df

   Transaction_Amount   Z_Score  Winsorized_Amount
0                 100 -0.474523                100
1                 150 -0.460833                150
2                 200 -0.447144                200
3                 250 -0.433454                250
4                 300 -0.419765                300
5                9999  2.235719               9999

In [ ]:
threshold = 500

df_truncate = df[df['Transaction_Amount'] <= threshold]
df_truncate

   Transaction_Amount   Z_Score  Winsorized_Amount
0                 100 -0.474523                100
1                 150 -0.460833                150
2                 200 -0.447144                200
3                 250 -0.433454                250
4                 300 -0.419765                300

## Label Encoder and Data Transformation Part 1

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    "Rating": ["Low", "Medium", "High", "Medium", "Low"]
})

le = LabelEncoder()
df['Encoded_Rating'] = le.fit_transform(df['Rating'])
df

   Rating  Encoded_Rating
0     Low               1
1  Medium               2
2    High               0
3  Medium               2
4     Low               1

In [ ]:
# y = x*a + b     0 -> 14 -> 14*a + b......understanding

In [ ]:
pd.get_dummies(df['Rating'], drop_first=True)

     Low  Medium
0   True   False
1  False    True
2  False   False
3  False    True
4   True   False

In [ ]:
pd.get_dummies(df['Rating'], drop_first=False)

    High    Low  Medium
0  False   True   False
1  False  False    True
2   True  False   False
3  False  False    True
4  False   True   False

## Label Encoder and Data Transformation Part 2

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

dfx = pd.DataFrame({
    "Value": [10,20,30,40,50]
})

In [ ]:
dfx['Value'].shape

(5,)

In [ ]:
scaler = MinMaxScaler()

In [ ]:
dfx['Scales_values'] = scaler.fit_transform(dfx['Value'].values.reshape(-1,1))

In [ ]:
dfx

   Value  Scales_values
0     10           0.00
1     20           0.25
2     30           0.50
3     40           0.75
4     50           1.00

## Label Encoder and Data Transformation Part 3

Feature ENGINEERING

In [ ]:
df1 = pd.DataFrame({
    "age": [25,30,35,40,45,75]
})

df1

   age
0   25
1   30
2   35
3   40
4   45
5   75

In [ ]:
bins = [0, 30, 50, 100]
labels = ['Young', 'Middle-aged', 'Senior']

df1['bin_age'] = pd.cut(df1['age'], bins=bins, labels=labels)
df1

   age      bin_age
0   25        Young
1   30        Young
2   35  Middle-aged
3   40  Middle-aged
4   45  Middle-aged
5   75       Senior

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

df2 = pd.DataFrame({"size": [550,700,900], "rooms": [2,3,4]})

poly_f = PolynomialFeatures(degree=2, include_bias=False)

df_poly = pd.DataFrame(poly_f.fit_transform(df2), columns=poly_f.get_feature_names_out())
df_poly

    size  rooms    size^2  size rooms  rooms^2
0  550.0    2.0  302500.0      1100.0      4.0
1  700.0    3.0  490000.0      2100.0      9.0
2  900.0    4.0  810000.0      3600.0     16.0